# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('solution', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalScore', models.IntegerField()),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('description', models.TextField()),
                ('solution', models.IntegerField()),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(max_length=255)),
                ('choice4', models.CharField(max_length=255)),
                ('choice5', models.CharField(max_length=255)),
                ('public', models.IntegerField(default=0)),
                ('correctTime', models.IntegerField(default=0)),
                ('tryTime', models.IntegerField(default=0)),
                ('changedAt', models.DateTimeField(auto_now=True)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_changer', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Klass')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
        migrations.AddField(
            model_name='examinationproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Problem'),
        ),
        migrations.AddField(
            model_name='examination',
            name='problems',
            field=models.ManyToManyField(through='mainApp.ExaminationProblem', to='mainApp.Problem'),
        ),
        migrations.AddField(
            model_name='answer',
            name='examinationProblem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ExaminationProblem'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
    ]
