# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('authority', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='examination',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_creator', to='mainApp.MyUser'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='changer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_changer', to='mainApp.MyUser'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_creator', to='mainApp.MyUser'),
        ),
    ]
